COPY COVID_DEATHS
FROM 'C:\Program Files\PostgreSQL\17\CovidDeaths.csv'
DELIMITER ',' CSV HEADER;



SELECT * FROM COVID_DEATHS;


COPY COVID_VACCINATION_DATA
FROM 'C:\Program Files\PostgreSQL\18\Copy of CovidVaccinations.csv'
DELIMITER ',' CSV HEADER;

SELECT * FROM COVID_VACCINATION_DATA;